# Travis file

language: cpp

compiler:
  - gcc
    
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libhdf5-serial-dev
  - ./install-gsl.sh
   
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

script: 
  - $CXX --version
  - make 

notifications:
  email: false
  

